sudo: false
language: c
addons:
  apt:
    packages:
    - libgmp-dev
env:
- ARGS="--resolver=lts-8"
- ARGS="--resolver=lts-9"
- ARGS="--resolver=lts-10"
- ARGS="--resolver=lts-11"
- ARGS="--resolver=nightly"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
  - stack $ARGS setup
  - stack $ARGS --no-terminal test --haddock --no-haddock-deps
  - stack $ARGS build
  - stack $ARGS sdist

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - .stack-work
