# We can't get on lts-11 with amazonka right now due to conduit compatibility
resolver: lts-10.10
packages:
- '.'
extra-deps: []
flags:
  bloodhound-amazonka-auth:
    "lib-Werror": true
extra-package-dbs: []
